<div class="grid grid-cols-12 gap-4">
<div class="xl:col-span-6 col-span-12"><label class="form-label">Product</label><select name="product_id" class="form-control"><option value="">Select product</option>@foreach ($products as $product)<option value="{{ $product->id }}" @selected(old('product_id', $sale->product_id ?? '') == $product->id)>{{ $product->product_name }}</option>@endforeach</select></div>
<div class="xl:col-span-6 col-span-12"><label class="form-label">Customer</label><select name="customer_id" class="form-control"><option value="">Walk-in / None</option>@foreach ($customers as $customer)<option value="{{ $customer->id }}" @selected(old('customer_id', $sale->customer_id ?? '') == $customer->id)>{{ $customer->customer_name }} ({{ ucfirst($customer->customer_type) }})</option>@endforeach</select></div>
<div class="xl:col-span-6 col-span-12"><label class="form-label">Sale Date</label><input type="datetime-local" name="sale_date" class="form-control" value="{{ old('sale_date', isset($sale) && $sale->sale_date ? $sale->sale_date->format('Y-m-d\TH:i') : now()->format('Y-m-d\TH:i')) }}" required></div>
<div class="xl:col-span-6 col-span-12"><label class="form-label">Sale Type</label><select name="sale_type" class="form-control" required><option value="retail" @selected(old('sale_type', $sale->sale_type ?? 'retail') === 'retail')>Retail</option><option value="wholesale" @selected(old('sale_type', $sale->sale_type ?? '') === 'wholesale')>Wholesale</option></select></div>
<div class="xl:col-span-6 col-span-12"><label class="form-label">Quantity</label><input type="number" step="0.01" min="0.01" name="quantity" class="form-control" value="{{ old('quantity', $sale->quantity ?? '') }}" required></div>
<div class="xl:col-span-6 col-span-12"><label class="form-label">Unit Price</label><input type="number" step="0.01" min="0" name="unit_price" class="form-control" value="{{ old('unit_price', $sale->unit_price ?? '') }}" required></div>
<div class="xl:col-span-6 col-span-12"><label class="form-label">Payment Status</label><select name="payment_status" class="form-control" required><option value="paid" @selected(old('payment_status', $sale->payment_status ?? 'paid') === 'paid')>Paid</option><option value="partial" @selected(old('payment_status', $sale->payment_status ?? '') === 'partial')>Partial</option><option value="unpaid" @selected(old('payment_status', $sale->payment_status ?? '') === 'unpaid')>Unpaid</option></select></div>
<div class="xl:col-span-12 col-span-12"><label class="form-label">Notes</label><textarea name="notes" class="form-control" rows="4">{{ old('notes', $sale->notes ?? '') }}</textarea></div>
</div>